### ISSUE TITLE
Do not overwrite https.globalAgent

### ISSUE THREAD

**Issue by ErunamoJAZZ** [pentagramacs/mercadolibre-nodejs#5]
Hi, it's me again.

We got other new problems after use this package. We were using passport to perform OAuth2 login with fb google etc. We noticed some errors in test after it, and looking at the code, I noticed you were overwriting the global agent options for https request and it was affecting request to OAuth providers.

So, I did test using those options not as global but just in ML request and it seems to work. As before, I will be doing a PR soon.

Thanks.

**Comment by viict** [comment]
Thanks again!
